### ISSUE TITLE
Disabling  a channel doesn't disable the selected measurement of that channel

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#205] opened 2017-07-27 07:32 UTC
scopy build: [dd0a1a82](https://github.com/analogdevicesinc/scopy/commit/dd0a1a82cbb3bf56649dedb1fa144af51680c2d9)

Steps to reproduce:

Activate measurement period and frequency for both ch1 and ch2

Then disable channel1, measurements of channel 1 stays on the display.

Same behavior happens even if both channels are disabled and there is no trace displayed. The measurements remain until deleted. Disabling a channel doesn't disable the selected measurement of that channel.

![bug osc](https://user-images.githubusercontent.com/25096080/28659064-9ba37104-72e0-11e7-801a-11f3e4a11202.JPG)

**Comment by dNechita** [comment] 2017-07-27 13:07
This is a duplicate of https://github.com/analogdevicesinc/scopy/issues/91

As far as I'm concerned this isn't a problem. It doesn't do anything harmful. In fact it gives you a little bit of flexibility by hiding the waveform (in case things get crowded on the plot canvas) while keeping the measurements. The measurements can be easily disabled at any time from the 'Horizontal' or 'Vertical' drop-downs. Moreover, you could use the 'Delete All' button for the channel you are about to hide.

**Comment by AlexandraTrifan** [comment] 2017-10-17 12:19
This is not applicable for the latest version.

**Closed** 2017-10-17 12:20 UTC
Labels: bug, duplicate, oscilloscope
