### ISSUE TITLE
AWG output phase between channels seems random

### ISSUE THREAD

**Issue by damercer** [analogdevicesinc/scopy#57] opened 2017-03-27 14:08 UTC
The relative phase between channel 1 and channel 2 seems to be random, different each time stop, run, stop, run .... Both channels are set to same settings, ampl, offset, freq, phase, shape. Both signals should lie on top of each other.

The reason I'm concerned about this is I'm trying to reproduce the transistor I/V curve tracer Lab and I need the base ( stair step ) and collector (ramp)  waveforms to be properly aligned at all times.

Doug

**Comment by pcercuei** [comment] 2017-03-27 15:22
Yes, I can reproduce. This happens on the integrated version, not on the FMC version.
The 'DMA sync' feature seems to be missing in the HDL.

**Comment by lclausen-adi** [comment] 2017-04-03 16:08
My fault. Fixed with https://github.com/analogdevicesinc/linux/commit/35653174ab0f7242cd1cd815951fd3ea80640a31

**Closed by lclausen-adi** 2017-04-03 16:08 UTC
Labels: bug, HDL bug, signal generator

**Comment by pcercuei** [comment] 2017-04-03 16:36
Thanks!
