### ISSUE TITLE
Voltmeter: Timer in min, the interval is inconsistent

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#1258] opened 2022-03-29 07:55 UTC
**Environment:**
 - OS: linux-arm32, windows10
 - FW Version : 0.28
 - SW Version or git tag: v1.4.0 rc1 895c0e9

**Describe the bug**
The interval in Timer if in minutes is inconsistent. It does not change by +/-1.

**To Reproduce**
1. Open voltmeter.
2. Go to data logging section and enable it.
3. Set timer to 1 s.
4. Set Timer unit to min.
5. Increase value using "+".
6. Notice that the interval in every increase is not +1 but instead 0.017.

**Expected behavior**
Change by +/-1.

**Screenshots**
![timer-min](https://user-images.githubusercontent.com/25096080/160561964-a37bcd29-c625-4db9-8111-47357a6fcfc4.png)

**Comment by adisuciu** [comment] 2022-03-29 07:57
duplicate of https://github.com/analogdevicesinc/scopy/issues/673

**Closed by adisuciu** 2022-03-29 07:57 UTC
Labels: bug, voltmeter
