### ISSUE TITLE
Signal Generator: Channel 2's color indicator for configuration menu is similar with channel 1's

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#188] opened 2017-07-18 02:08 UTC
OS: Windows 7 64bit
 Scopy Version:  3eb2610
 Firmware Version: v0.14

The color indicator for channel 2's configuration is similar with channel 1 which is orange.
I think it would be good if the color is similar to the waveform and the on/off button for channel 2 to avoid confusion.

![signal gen enhancement](https://user-images.githubusercontent.com/20266602/28297495-d9af83f8-6ba0-11e7-9916-8355f2760065.png)

**Comment by dNechita** [comment] 2017-07-18 06:09
This is a duplicate of #10

**Comment by pcercuei** [comment] 2017-07-18 09:16
The tabs are underlined with orange in the theme, independently of the colors of the channels. Maybe we should change that to the same blue we use everywhere.

**Comment by DanielGuramulta** [comment] 2017-08-25 08:40
Fixed with commit: 6fd7ece

**Comment by amiclaus** [comment] 2017-08-28 11:50
On Scopy build: be46948(v0.7) the bug is fixed.

**Closed by amiclaus** 2017-08-28 11:50 UTC
Labels: duplicate, enhancement, fixed, signal generator
