### ISSUE TITLE
Acquisition halts during a continuous capture

### ISSUE THREAD

**Issue by dNechita** [analogdevicesinc/scopy#134] opened 2017-06-28 21:18 UTC
After clicking the Run button the acquisition seems to stop (new data no longer comes in). This doesn't happen on the first try. Multiple attempts will eventually bring this problem to surface.

The following appears to cause the issue above: https://github.com/analogdevicesinc/scopy/commit/a0d895583fb7ba728b5ac80f6c80996ac2770f21. 
@pcercuei can you take a look?

**Comment by pcercuei** [comment] 2017-06-30 10:13
Is there a specific pattern that triggers it? I can't reproduce.

**Comment by pcercuei** [comment] 2017-07-06 10:16
Fixed in https://github.com/analogdevicesinc/gr-iio/commit/54c86a517edf7933f4ce5e87c8c57d243c85b3ba

**Comment by amiclaus** [comment] 2017-07-24 10:42
On Scopy build: 3aae9de (v0.6) the bug is fixed.

**Closed by amiclaus** 2017-07-24 10:42 UTC
Labels: bug, fixed, oscilloscope, spectrum analyzer
