### ISSUE TITLE
Scopy crashes when opening preferences

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#402] opened 2018-03-27 01:44 UTC
Scopy  build: [1d0a075f](https://github.com/analogdevicesinc/scopy/commit/1d0a075ff196205524604598a4d023249b58adf9)

Steps to reproduce:

Click Connect
Click Disconnect 
Click again Connect
Then open preferences
Scopy crashes few moments after clicking preferences

![qw](https://user-images.githubusercontent.com/25096080/37941928-3d1fe248-31a3-11e8-8045-76311118f62b.PNG)

**Comment by adisuciu** [comment] 2018-03-27 09:02
Can you provide an .ini file for the build that crashes ? 
On Windows it's in C:\Users\<User>\AppData\Roaming\ADI\Scopy.ini

**Comment by tagoylo** [comment] 2018-03-27 09:15
here it is,

[Scopy.zip](https://github.com/analogdevicesinc/scopy/files/1851259/Scopy.zip)

**Comment by adisuciu** [comment] 2018-03-27 09:37
Also, same path, preferences.ini

**Comment by tagoylo** [comment] 2018-03-27 09:48
[ini_files.zip](https://github.com/analogdevicesinc/scopy/files/1851398/ini_files.zip)

**Comment by adisuciu** [comment] 2018-03-27 12:05
We cannot reproduce. Do you load something before the crash occurs ?

**Comment by DanielGuramulta** [comment] 2018-03-28 14:15
I was able to reproduce the bug by changing the number of periods for the signal generator. Connect -> Disconnect -> Connect and while some tools are calibrating change the number of periods in the preferences menu. Can you try to reproduce the bug using this build: https://ci.appveyor.com/project/analogdevicesinc/scopy/build/1.0.1737/artifacts @tagoylo

**Comment by tagoylo** [comment] 2018-04-02 12:03
I wasn't able to reproduce the bug with the given build.

**Comment by adisuciu** [comment] 2018-04-05 09:57
Should be fixed with e700029

**Comment by amiclaus** [comment] 2018-05-02 09:11
On Scopy build: 87e17a9b the bug is fixed.

**Closed by amiclaus** 2018-05-02 09:11 UTC
Labels: bug, fixed, general
