### ISSUE TITLE
Waveform generator noise was not added when i visualized in scope sometimes

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#564] opened 2019-04-04 07:42 UTC
Hello

pls find the screenshot waveform generator impulse noise added in the signal generator

but not able to visualize in oscillosope

pls find the screenshot

![image](https://user-images.githubusercontent.com/4321670/55538113-511a1080-56db-11e9-9d1b-2819a81cd174.png)

**Comment by adisuciu** [comment] 2019-04-04 08:39
Duplicate of https://github.com/analogdevicesinc/scopy/issues/338 . 
Patch will be available in next SW release.

**Comment by pantechsolutions** [comment] 2019-04-04 11:19
Thank you.

**Comment by amiclaus** [comment] 2019-05-09 12:13
On Scopy version: e28686c (v1.0.5) the bug is fixed.

**Closed by amiclaus** 2019-05-09 12:13 UTC
Labels: bug, fixed
