### ISSUE TITLE
Item 1 From Issue #4: Screen Resize When Opening Signal Generator

### ISSUE THREAD

**Issue by jonpearson** [analogdevicesinc/scopy#21] opened 2016-11-09 20:43 UTC
Item 1 from Issue #4

"When you open the signal generator controls, the screen re-sizes and the bottom where you select channel 1 or 2 goes below the Task Bar and the icons can’t be seen or easily clicked on."

**Comment by jonpearson** [comment] 2016-11-09 20:45
I was not able to reproduce this issue in the current revision of Scopy.  The channel selection options were above the Task Bar when I opened the signal generator.

**Comment by rgetz** [comment] 2016-11-10 13:05
This will depend on the screen size. 

I think Doug's laptops are 720p displays. (1280×720 px). If you are using 1080 - you will not be able to reproduce. 

Change the resolution on your screen to 720p, and try it out.

**Comment by damercer** [comment] 2016-11-10 14:18
Correct. The software needs to know the screen size so it does not grow the window beyond the visible space. In my opinion the program should not change the window size beyond what
the user has set. And remember that for future sessions.

**Comment by pcercuei** [comment] 2016-11-23 09:30
I'll mark this as duplicate of #17 and close this one.

**Closed by pcercuei** 2016-11-23 09:30 UTC
Labels: duplicate
