### ISSUE TITLE
Group Channels not working properly

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#133] opened 2017-06-28 08:45 UTC
Scopy Version:  fb92e653; OS: Windows; Firmware v0.13;

Make a loopback between Channel Group DIO0-7 and DIO8-15
![group-pinconnection](https://user-images.githubusercontent.com/26061529/27639750-d2d4f558-5c1f-11e7-82b8-4f46cd7ad980.png)

Set Group DIO0-7 as output with value 0 and DIO8-15 as input. Run the instrument. 
![bug](https://user-images.githubusercontent.com/26061529/27628157-cf9f5456-5bf6-11e7-9079-1abeb71a3532.PNG)
Change slightly the value of DIO0-7:
![bug2](https://user-images.githubusercontent.com/26061529/27628264-251aabc4-5bf7-11e7-94c9-9f2d90c18560.PNG)

There is no proper correlation between the 2 channel groups.

**Comment by adisuciu** [comment] 2017-06-28 11:38
@larsclausen  @acostina This seems to be an HDL/firmware issue. The issue can be reproduced by doing the following in iio-scope

```
setup - short channel 0 to channel 8
device - m2k-logic-analyzer

set channel 0 direction output
set channel 0 raw 1
read channel 8 raw 1
set channel 0 direction input

set channel 0 direction output
set channel 0 raw 0
read channel 8 - raw - 0

set channel 0 direction input
set channel 0 raw 0
read channel 8 - raw - 1  - mismatch
```

**Comment by lclausen-adi** [comment] 2017-06-28 11:44
Hm, so the problem is when both channel 0 and channel 8 are set to input they don't read the same value for raw?

**Comment by adisuciu** [comment] 2017-06-28 11:45
Sorry, typo, updated test steps

**Comment by mhennerich** [comment] 2017-06-28 11:54
Works without issues for me.
Tried it with the latest firmware image I just shared.

-Michael

**Comment by adisuciu** [comment] 2017-06-28 13:10
I flashed latest firmware, still get the same behavior. I should mention I still use rev A. board. I created small test program to reproduce the error. 

`dev = iio_context_find_device(ctx, "m2k-logic-analyzer");
	auto ch0 = iio_device_find_channel(dev,"voltage0", 0);
	auto ch8 = iio_device_find_channel(dev, "voltage8", 0);
	char buffer[10];

	iio_channel_attr_write(ch0, "direction", "in");
	iio_channel_attr_write(ch8, "direction", "in");

	printf("set channel0 direction output\n");
	iio_channel_attr_write(ch0, "direction", "out");
	printf("set channel0 raw 1\n");
	iio_channel_attr_write(ch0, "raw", "1");
	iio_channel_attr_read(ch8, "raw", buffer, 10);
	printf("read channel 8 - %s\n",buffer);
	printf("set channel 0 direction input\n");
	iio_channel_attr_write(ch0, "direction", "in");


	printf("set channel0 direction output\n");
	iio_channel_attr_write(ch0, "direction", "out");
	printf("set channel0 raw 0\n");
	iio_channel_attr_write(ch0, "raw", "0");
	iio_channel_attr_read(ch8, "raw", buffer, 10);
	printf("read channel 8 - %s\n", buffer);
	printf("set channel 0 direction input\n");
	iio_channel_attr_write(ch0, "direction", "in");


	printf("set channel0 direction output\n");
	iio_channel_attr_write(ch0, "direction", "out");
	printf("set channel0 raw 0\n");
	iio_channel_attr_write(ch0, "raw", "0");
	iio_channel_attr_read(ch8, "raw", buffer, 10);
	printf("read channel 8 - %s\n", buffer);
	printf("set channel 0 direction input\n");
	iio_channel_attr_write(ch0, "direction", "in");`

**Comment by mhennerich** [comment] 2017-06-28 13:31
I also have RevA. And I guess (hope) you're NOT shorting the outputs like shown in the picture above!
So only DIO0<->DIO8, etc. ...

-Michael

**Comment by adisuciu** [comment] 2017-06-28 13:41
I shorted just the digital inputs. I also tried shorting only 0 to 8, same behavior.

**Comment by lclausen-adi** [comment] 2017-06-29 10:12
It's and issue with the HDL and will be fixed. For now as a workaround you need to set raw to 1 temporarily to have the direction change applied.

E.g.

direction = out
raw = 1 // Direction change happens
raw = X

**Comment by lclausen-adi** [comment] 2017-06-29 11:36
Fixed by https://github.com/analogdevicesinc/hdl/commit/8755e6da44dca11dfab18765485f77bd516f9478

**Closed by lclausen-adi** 2017-06-29 11:36 UTC
Labels: bug, digital IO
