### ISSUE TITLE
Oscilloscope: Fails to autoset horizontal and vertical settings on math generated waveform from SG

### ISSUE THREAD

**Issue by HRosete** [analogdevicesinc/scopy#907] opened 2020-10-05 06:23 UTC
**Environment:**
 - OS: Windows 10
 - FW Version: m2k-fw-v0.25-3-g1c38-dirty
 - SW Version or git tag: 7eec50d

**Describe the bug**
The oscilloscope fails to autoset the Horizontal (Time Base) and Vertical (Volts/Div) settings when the signal generated is from the Math function of the Signal Generator. The result is a cut waveform on the Oscilloscope's screen when it should have displayed several periods of the waveform upon clicking 'Autoset.'

**To Reproduce**
1. Open Scopy and connect the M2K to your laptop.
2. Unzip the attached file 'scopy_sig-gen_math.zip' and load the .ini file to Scopy. 
[scopy_sig-gen_math.zip](https://github.com/analogdevicesinc/scopy/files/5325541/scopy_sig-gen_math.zip)

3. Connect AWG CH1 to scope CH1+ and scope CH1- to GND.
4. Click 'Run' on the Signal Generator.
5. Click 'Run' on the Oscilloscope.
6. Click 'Autoset' and observe the waveform read by the oscilloscope.

**Expected behavior**
The oscilloscope should automatically adjust the horizontal and vertical settings to display several periods of the waveform upon clicking 'Autoset.'

**Screenshots**
Waveform using the Math function of the SG:
![image](https://user-images.githubusercontent.com/43806793/95046032-dc7fc200-0715-11eb-8934-e02f38a5c2d5.png)

Waveform read by the oscilloscope after clicking 'Autoset':
![image](https://user-images.githubusercontent.com/43806793/95046209-51eb9280-0716-11eb-84ab-96ebc1b32d05.png)

Expected behavior; the same waveform after adjusting the Horizontal and Vertical settings manually:
![image](https://user-images.githubusercontent.com/43806793/95046187-3d0eff00-0716-11eb-9b49-abb2eb0f07de.png)

**Comment by HRosete** [comment] 2020-10-06 03:28
FW: [m2k-fw-v0.25-3-g1c38-dirty.zip](https://github.com/analogdevicesinc/scopy/files/5331220/m2k-fw-v0.25-3-g1c38-dirty.zip)
Math equation on SG: f(t) = sin(2*pi*1000*t)

**Comment by adisuciu** [comment] 2020-10-13 12:25
duplicate of https://github.com/analogdevicesinc/scopy/issues/913

**Closed by adisuciu** 2020-10-13 12:25 UTC
Labels: bug, oscilloscope
