### ISSUE TITLE
Scopy hangs when connecting on windows 7

### ISSUE THREAD

**Issue by pantechsolutions** [analogdevicesinc/scopy#624] opened 2019-06-26 09:52 UTC
Hello

i am using windows 7,Scopy hangs while connecting the device.it just display calibrating and then it hangs on.

Environmetal variable setting is corrrect.Scopy can detect adalm2000 .
but when click connect it just started calibrating and then  it hangs.

any help,thanks

**Comment by adisuciu** [comment] 2019-06-26 10:45
Did it work before , or is this just happening ? Does the board work on a different computer ?

Make sure you have these drivers installed: https://github.com/analogdevicesinc/plutosdr-m2k-drivers-win/releases
Make sure your restart your computer after installing Scopy. 
If all else fails, can you try connecting via ip: 192.168.2.1 ?

**Comment by pantechsolutions** [comment] 2019-06-26 10:59
i am reseller ,i sold out more than 50 customer so far,it worked fine.
 when i installed in one of my customer computer which has windows 7,it was not working.

i have download and install latest version.
I have restart.
I have check environmental variables
i have also cleared files in app data

one think i noticed some different was the screenshot
![image](https://user-images.githubusercontent.com/4321670/60174756-5d6fbe80-982f-11e9-8623-a9a2ef758ec5.png)
in universal serial bus devices ,the working computer has an IIO,Whereas in this pc,it was mentioned m2k iio usbd.

**Comment by pantechsolutions** [comment] 2019-06-26 11:01
If all else fails, can you try connecting via ip: 192.168.2.1 ?

This also fails.

**Comment by adisuciu** [comment] 2019-06-26 13:24
Can you download this -  https://github.com/analogdevicesinc/libiio/releases/download/v0.18/libiio-0.18.g4e22517-Windows.zip

Run a command prompt, navigate to C:\...\libiio-0.18.g4e22517\MS64 (or MS32 depending on your OS version), and run iio_info -a and send us the output of that command ?

**Comment by pantechsolutions** [comment] 2019-06-26 14:30
![image](https://user-images.githubusercontent.com/4321670/60188470-f7922f80-984c-11e9-97be-b7bec7a01aa6.png)

**Comment by pantechsolutions** [comment] 2019-06-26 14:42
![image](https://user-images.githubusercontent.com/4321670/60189541-af740c80-984e-11e9-8185-bfac3c8cdd3f.png)

**Comment by pantechsolutions** [comment] 2019-06-26 14:48
![image](https://user-images.githubusercontent.com/4321670/60189981-7c7e4880-984f-11e9-924f-4ab62fc25f6b.png)

**Comment by pantechsolutions** [comment] 2019-06-26 14:48
Those are the errors while try to installing IIO in windows 7

**Comment by pantechsolutions** [comment] 2019-06-26 15:01
![image](https://user-images.githubusercontent.com/4321670/60191132-6d989580-9851-11e9-8a6c-0739f330d486.png)

**Comment by pantechsolutions** [comment] 2019-06-27 04:35
Hello any help on this issue

**Comment by pantechsolutions** [comment] 2019-06-27 07:05
Hello sir, Am getting different results while running the command which u told. But still its closing automatically while calibrating with the device.
![image](https://user-images.githubusercontent.com/4321670/60244412-ff4ae600-98d7-11e9-9b90-7fdd2478fb1b.png)

![image](https://user-images.githubusercontent.com/4321670/60244424-04a83080-98d8-11e9-9f39-10880df49601.png)

**Comment by adisuciu** [comment] 2019-06-27 09:11
Hello,

It looks like the USB connection to the M2k is working. Can you modify in C:\Users\welcome\AppData\Roaming\ADI\scopy.ini -> skip_calibration=true . Try to reconnect, see if it fails. The device should not work correctly(it should not give out the correct voltages) but we can diagnose further if there is a calibration issue or not.

-Adrian

**Comment by pantechsolutions** [comment] 2019-06-27 11:19
There is nothing present inside that scopy.ini file

**Comment by adisuciu** [comment] 2019-06-27 11:44
Try running Scopy, and closing it correctly without connecting to the board. That should populate Scopy.ini . Also replace <welcome> from the path with your username.

-Adrian

**Comment by pantechsolutions** [comment] 2019-06-28 16:11
Hai, in some pc its not present. In some its present but still its for calibration. While calibrating oscilloscope. It Closes

**Comment by pantechsolutions** [comment] 2019-06-29 03:50
Hi, Its urgent, we bought more products, ts essential to fix this issue soon. Actual problem is, in some system it is showing that ADI directory, but in some system Not. Then even if we changed the Skip calibration to True still after connecting ts showing same error

**Comment by adisuciu** [comment] 2019-07-01 09:07
Hello, 

Unfortunately we cannot reproduce your issue. Please try uninstalling the driver and Scopy and then reinstall. You can uninstall it from add/remove programs. Also try updating the board firmware to the latest version.
https://wiki.analog.com/university/tools/pluto/users/firmware

If things work after the reinstall don't forget to remove the file mentioned previously so things start out fresh.

-Adrian

**Closed** 2019-09-25 12:52 UTC
