### ISSUE TITLE
Pattern generator fails to generate correct clock frequency greater than 1MHz

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#212] opened 2017-08-01 08:23 UTC
Scopy build: [9f2f0b17](https://github.com/analogdevicesinc/scopy/commit/9f2f0b17e3edbf50159bc79ead8c3b2f4fdff229)

Steps to reproduce:
Enable DIO0. Set as clock. Set clock frequency to 2MHz/5MHz/10MHz.

Monitor through oscilloscope. Enable built-in measurement feature to see frequency. The result is shown below when pattern generator frequency is set to 2MHz:

![ba](https://user-images.githubusercontent.com/25096080/28815775-0b0471ea-76d5-11e7-83b9-5808862ff0a8.JPG)

Also monitor through logic analyzer. Use cursors to know frequency. Use 200ns/div time base. The result is shown below when pattern generator frequency is set to 2MHz:

![bb](https://user-images.githubusercontent.com/25096080/28815780-11977dfe-76d5-11e7-9908-b84f3bde51c1.JPG)

Duty cycle is also not consistent.

**Comment by adisuciu** [comment] 2017-08-01 15:00
@acostina  It looks like this is an HDL issue.

**Comment by lclausen-adi** [comment] 2017-08-02 03:40
What's the size of the buffer you are creating for this waveform? For good performance the buffer size should be at least 128 bytes. If it is smaller repeat it in software until the minimum is reached.

**Comment by adisuciu** [comment] 2017-08-02 08:07
For 10 MHz , the buffersize is 8. It looks like I forgot to update the "main" sampling frequency to 100MHz (it's still 80), but that doesn't seem to cause the issue. This is some code I've used to reproduce:
https://pastebin.com/raw/cbQjuZPa

**Comment by lclausen-adi** [comment] 2017-08-17 09:42
Increasing the minimum number of samples per buffer to 128 seems to avoid the issue.

**Comment by rgetz** [comment] 2017-08-17 12:41
Lars:

Should the kernel just reject buffers (fail and return error code) it knows are too small?

**Comment by lclausen-adi** [comment] 2017-08-17 12:45
The kernel doesn't know that the buffers are too small. This is a system design problem. It depends on the buffer size, the DDR memory performance and the data read rate. Smaller buffers will work fine with smaller samplerates or faster DDR speed.

**Comment by rgetz** [comment] 2017-08-17 12:48
Got it. Thanks

**Comment by adisuciu** [comment] 2017-08-29 10:22
Fixed with a050a81158054fee5616b1909f9dad5bc4a3ffa2

**Comment by amiclaus** [comment] 2017-08-30 16:26
On Scopy build: 5bb6466 (v0.7) the bug is fixed.

**Closed by amiclaus** 2017-08-30 16:26 UTC
Labels: bug, fixed, pattern generator
